[project]
name = "bilibili-music-player"
version = "0.1.0"
description = "从 bilibili 获取音频的 web 音乐播放器"
readme = "README.md"
authors = [
    { name = "shaomingyang.10", email = "shaomingyang.10@jd.com" }
]
requires-python = ">=3.10"
dependencies = [
    "bilibili-api-zoku",
    "fastapi>=0.115.0",
    "uvicorn>=0.30.0",
    "httpx>=0.28.1",
    "curl-cffi>=0.7.0",
]

[project.scripts]
bilibili-music-player = "bilibili_music_player:main"

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
    "pytest>=8.0",
]

[tool.uv.sources]
bilibili-api-zoku = { url = "https://github.com/bromothymolb/bilibili-api-zoku/archive/a0a1566c7c462ab57a3891c3a5f12976cbd11e9e.tar.gz" }

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
